config/routes.rb
Rails.application.routes.draw do
  get ':slug' => 'links#show'
  resources :links

  root 'home#index'

end

app/models/link.rb
# link model
class Link < ActiveRecord::Base
  paginates_per 10
  after_create :generate_slug
  def generate_slug
    loop do
      self.slug = SecureRandom.hex(5)
      break unless self.class.exists?(slug: slug)
    end
    save
  end

  def display_slug
    (Rails.root + slug).to_s
  end
end

app/controllers/application_controller.rb
# application
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
# home controller
class HomeController < ApplicationController
  def index
    @link = Link.new
    @top_links = Link.order(created_at: :desc).page params[:page]
  end
end

app/controllers/links_controller.rb
# links controller
class LinksController < ApplicationController
  before_action :set_link, only: [:show]

  def index
    @links = Link.all
  end

  def show
    if params[:slug]
      @link = Link.find_by(slug: params[:slug])
      if redirect_to @link.given_url
        @link.clicks += 1
        @link.save
      end
    else
      @link = Link.find(params[:id])
    end
  end

  def create
    @link = Link.new(link_params)
    @link.clicks = 1
    respond_to do |format|
      if @link.save
        format.html do
          redirect_to root_path, notice: 'Link was successfully created.'
        end
        format.js
        format.json { render action: 'show', status: :created, location: @link }
      else
        format.html { render action: 'new' }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_link
    @link = Link.find_by(slug: params[:slug])
  end

  def link_params
    params.require(:link).permit(:given_url)
  end
end

app/helpers/application_helper.rb
# application helper
module ApplicationHelper
  def custom_url
    Rails.env == 'production' ? request.host : "#{request.host}: #{request.port}"
  end
end

app/views/home/index.html.erb
<div class="table-responsive">
  <table class="table">
    <thead>
      <tr>
        <th>Given url</th>
        <th>Short Link</th>
        <th>Clicks</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody class="links-data">
      <%  @top_links.each do |link| %>
        <tr>
          <td><%= link.given_url %></td>
          <td><%= link_to "#{custom_url}/#{link.slug}", link.slug, target: '_blank' %></td>  
          <td><%= link.clicks %></td>
          <td><%= link_to 'Show', link %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<%=  paginate @top_links %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Url Shortener</title>
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
        <%= csrf_meta_tags %>
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button aria-controls="navbar" aria-expanded="false" data-target="#navbar" data-toggle="collapse" class="navbar-toggle collapsed" type="button">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a href="#" class="navbar-brand">Url Shortener</a>
                </div>
                <div class="collapse navbar-collapse" id="navbar">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="#">Home</a></li>
                        <li><a href="#about">About</a></li>
                        <li><a href="#contact">Contact</a></li>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>

        <div class="container top-margin-120">
            <div class="row">
                <div class="col-md-5 centered">
                    <b><h1 class="text-center"> Url Shortener</h1></b>
                    <%= render 'links/form' %>
                </div>
            </div>

            <div class="result">
            </div>

            <%= yield %>
        </div>
    </body>
</html>

app/views/links/_form.html.erb
<%= form_for(@link, remote: true, class: 'form-horizontal new_link') do |f| %>
  <% if @link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% @link.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group ">
    <%= f.text_field :given_url, :class => "form-control", :placeholder => "Paste a link to shorten" %>
  </div>
  <div class="form-group text-center">
    <%= f.submit 'Shorten Me', :class => "btn btn-primary"%>
  </div>
<% end %> 

app/views/links/create.js.erb
$('.result').append('<p class="short_url">Your Shortened Link: <%= link_to "#{custom_url}/#{@link.slug}", @link.slug, target: "_blank" %></p>')
$('#link_given_url').val('');
$('.links-data').prepend('<tr>' +
  '<td><%= @link.given_url %></td>' +
  '<td><%= link_to "#{custom_url}/#{@link.slug}", @link.slug, target: "_blank" %></td>' +
  '<td><%= @link.clicks %></td>' +
  '<td><%= link_to 'Show', @link %></td>' +
  '</tr>'
)

app/views/links/edit.html.erb
<h1>Editing Link</h1>

<%= render 'form' %>

<%= link_to 'Show', @link %> |
<%= link_to 'Back', links_path %>

app/views/links/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Links</h1>

<table>
  <thead>
    <tr>
      <th>Given url</th>
      <th>Slug</th>
      <th>Clicks</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @links.each do |link| %>
      <tr>
        <td><%= link.given_url %></td>
        <td><%= link.slug %></td>
        <td><%= link.clicks %></td>
        <td><%= link_to 'Show', link %></td>
        <td><%= link_to 'Edit', edit_link_path(link) %></td>
        <td><%= link_to 'Destroy', link, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Link', new_link_path %>

app/views/links/new.html.erb
<h1>New Link</h1>

<%= render 'form' %>

<%= link_to 'Back', links_path %>

app/views/links/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Given url:</strong>
  <%= @link.given_url %>
</p>

<p>
  <strong>Slug:</strong>
  <%= @link.slug %>
</p>

<p>
  <strong>Clicks:</strong>
  <%= @link.clicks %>
</p>

<%= link_to 'Back', root_path %>